# Generated by Django 4.2.4 on 2023-09-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
